Tier 1 Cost: 0
Tier 2 Cost: 0
Tier 3 Cost: 0
Tier 4 Cost: 0
Drop Radius: 0.0
Countdown Time: 0
Drop Height: 0.0
Costs:
  ' Tier1': 10
  ' Tier2': 10
  ' Tier3': 10
  ' Tier4': 10
Drop Chances:
  ' Tier1': [20, 20, 20, 20, 20]
  ' Tier2': [20, 20, 20, 20, 20]
  ' Tier3': [20, 20, 20, 20, 20]
  ' Tier4': [20, 20, 20, 20, 20]
