Item Lists:
  Common: []
  Uncommon: []
  Rare: []
  Epic: []
  Legendary: []
Costs:
  Tier 1: 0
  Tier 2: 0
  Tier 3: 0
  Tier 4: 0
Drop Radius: 0.0
Countdown Time: 0
Drop Height: 0.0
Drop Chances:
  Tier 1: []
  Tier 2: []
  Tier 3: []
  Tier 4: []
